export const COMMODITIES_DETAILS_LOADED = 'commodity.COMMODITIES_DETAILS_LOADED';
export const COMMODITY_DETAILS_LOADED = 'commodity.COMMODITY_DETAILS_LOADED';
export const UPDATE_COMMODITY_DETAILS = 'commodity.UPDATE_COMMODITY_DETAILS';
export const SUBMIT_UPDATE_COMMODITY = 'commodity.SUBMIT_UPDATE_COMMODITY';
export const NEW_METADATA = 'commodity.NEW_METADATA';
export const COMMODITIES_SAVED = 'commodity.COMMODITIES_SAVED';
export const LOAD_COMMODITIES = 'commodity.LOAD_COMMODITIES';
export const LOAD_COMMODITY = 'commodity.LOAD_COMMODITY';
